import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { auth } from "@/auth";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();

  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="antialiased">

        <Navbar />
        <div className={`${session ? "lg:ml-56 pt-14 lg:pt-0" : ""} min-h-screen flex flex-col`}>
          <main className="flex-1 p-3 lg:p-6 bg-linear-to-br from-white to-violet-50">{children}</main>
          <footer className="border-t border-zinc-200 py-4 px-6">
            <p className="text-xs text-zinc-400 text-center">Are You Coming?</p>
          </footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
