import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="lg:ml-56 pt-14 lg:pt-0 min-h-screen flex flex-col">
          <main className="flex-1 p-6 bg-linear-to-br from-white to-violet-50">{children}</main>
          <footer className="border-t border-zinc-200 py-4 px-6">
            <p className="text-xs text-zinc-400 text-center">Are You Coming?</p>
          </footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
